#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses
echo "127.0.0.2	localhost" > /tmp/hosts
grep -vE '^[[:space:]]*127\.0\.0\.1[[:space:]]+localhost' /etc/hosts >> /tmp/hosts
grep -vE '^[[:space:]]*8\.8\.8\.8[[:space:]]+facebook\.com' /tmp/hosts > /tmp/hosts2
echo "8.8.8.8	facebook.com" >> /tmp/hosts2
cat /tmp/hosts2 > /etc/hosts
rm -f /tmp/hosts /tmp/hosts2
